SELECT DISTINCT(H.CAR_ID), NVL2(C.CAR_ID, '대여중', '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    LEFT JOIN (SELECT DISTINCT(CAR_ID)
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE START_DATE <= DATE '2022-10-16' AND END_DATE >= DATE '2022-10-16') C
                ON H.CAR_ID = C.CAR_ID
ORDER BY H.CAR_ID DESC